# Base16 Generated - kitty color config
# Scheme by Flavours
background #1b1e23
foreground #d1cabf
selection_background #d1cabf
selection_foreground #1b1e23
url_color #ada8a0
cursor #d1cabf
cursor_text_color #1b1e23
active_border_color #888580
inactive_border_color #3f4042
active_tab_background #1b1e23
active_tab_foreground #d1cabf
inactive_tab_background #3f4042
inactive_tab_foreground #ada8a0
tab_bar_background #3f4042
wayland_titlebar_color #1b1e23
macos_titlebar_color #1b1e23

# normal
color0 #1b1e23
color1 #cf4c4a
color2 #84747e
color3 #7d7963
color4 #7e8d99
color5 #9da5b6
color6 #917077
color7 #d1cabf

# bright
color8 #888580
color9 #778192
color10 #3f4042
color11 #646361
color12 #ada8a0
color13 #d8d2c8
color14 #7b777d
color15 #dfdad2